version: 2
updates:
  # Main
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo

  # npm
  - package-ecosystem: npm
    directory: "/npm"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    versioning-strategy: increase

  # Python
  - package-ecosystem: pip
    directory: "/python"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo

  # Docker
  - package-ecosystem: docker
    directory: "/base"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: docker
    directory: "/dotnet"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: docker
    directory: "/go"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: docker
    directory: "/java"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: docker
    directory: "/npm"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    ignore:
      - dependency-name: node
        # NOTE: Node 14 is the current LTS version. See <https://github.com/nodejs/Release#readme>.
        versions: ["> 14"]
  - package-ecosystem: docker
    directory: "/php"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    ignore:
      - dependency-name: php
        # TODO: We now supports PHP 7 because PHP 8 is a big release (#387). See also <https://www.php.net/releases/8.0/en.php>.
        versions: ["> 7"]
  - package-ecosystem: docker
    directory: "/python"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: docker
    directory: "/swift"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
