name: Build

on:
  push:
    branches: ["master"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - base
          - dotnet
          - go
          - java
          - npm
          - php
          - python
          - ruby
          - swift
    env:
      BUILD_CONTEXT: ${{ matrix.build-context }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Define environment variables
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            tag="${GITHUB_REF/refs\/tags\//}"
            tag_latest=true
            echo "TAG=${tag}" >> $GITHUB_ENV
            echo "TAG_LATEST=${tag_latest}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            tag="${GITHUB_REF/refs\/heads\//}"
            echo "TAG=${tag}" >> $GITHUB_ENV
          fi
          # Debug
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "TAG: ${tag}"
          echo "TAG_LATEST: ${tag_latest}"
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: bundle exec rake dockerfile:generate dockerfile:verify
      - name: Define build variables
        id: build_vars
        run: |
          echo "::set-output name=file::$(bundle exec rake docker:file)"
          echo "::set-output name=tag::$(bundle exec rake docker:image_name)"
          echo "::set-output name=tag_latest::$(bundle exec rake docker:image_name TAG=latest)"
      - uses: docker/build-push-action@v2
        with:
          file: ${{ steps.build_tags.outputs.file }}
          tags: ${{ steps.build_tags.outputs.tag }}
          cache-from: type=registry,ref=${{ steps.build_vars.outputs.tag_latest }}
          cache-to: type=inline
      - run: bundle exec rake docker:run
      - run: bundle exec rake docker:run'[sudo update-ca-certificates]'
      - run: bundle exec rake docker:run'[sudo apt-get clean]'
      - run: bundle exec rake docker:run'[echo file > /usr/local/share/ca-certificates/file.crt]'
      - uses: docker/build-push-action@v2
        # if: ${{ github.event_name == 'push' }}
        with:
          # push: true
          file: ${{ steps.build_tags.outputs.file }}
          tags: ${{ steps.build_tags.outputs.tag }},${{ steps.build_vars.outputs.tag_latest }}
