name: Build

on:
  push:
    branches: ["master"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - base
          - dotnet
          - go
          - haskell
          - java
          - npm
          - php
          - python
          - ruby
          - swift
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Show Docker information
        run: docker info
      - name: Define variables
        id: define_vars
        # See https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          tag="${GITHUB_REF#refs/*/}"
          tag="${tag///}"
          echo "::set-output name=tag::${tag}"
      - name: Print variables
        run: echo tag=${{ steps.define_vars.outputs.tag }}
      - name: Build and test the Docker image
        run: |
          bundle exec rake dockerfile:generate dockerfile:verify
          bundle exec rake docker:build docker:run
          bundle exec rake docker:run'[sudo update-ca-certificates]'
          bundle exec rake docker:run'[sudo apt-get clean]'
          bundle exec rake docker:run'[echo file > /usr/local/share/ca-certificates/file.crt]'
        env:
          BUILD_CONTEXT: ${{ matrix.build-context }}
          TAG: ${{ steps.define_vars.outputs.tag }}
      - name: Login to Docker Hub
        if: ${{ steps.define_vars.outputs.tag == 'master' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish the Docker image
        if: ${{ steps.define_vars.outputs.tag == 'master' || startsWith(github.ref, 'refs/tags/') }}
        run: bundle exec rake docker:push
        env:
          BUILD_CONTEXT: ${{ matrix.build-context }}
          TAG: ${{ steps.define_vars.outputs.tag }}
          TAG_LATEST: ${{ startsWith(github.ref, 'refs/tags/') }}
