name: Bump Bundler

on:
  schedule:
    - cron: "0 0 * * 1,3,5"
  workflow_dispatch:
  push:
    branches: ["auto-bumping-bundler"]

jobs:
  bump-bundler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Get current version
        id: current_version
        run: |
          current_version=$(grep 'bundler' Gemfile | grep -o -E '[0-9.]+')
          echo "::set-output name=value::${current_version}"
      - name: Get latest version
        id: latest_version
        run: |
          latest_version=$(gh api repos/rubygems/rubygems/releases/latest --jq '.tag_name' | sed 's/bundler-v//')
          echo "::set-output name=value::${latest_version}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update file
        run: |
          sed -E "s/'${{ steps.current_version.outputs.value }}'/'${{ steps.latest_version.outputs.value }}'/" Gemfile
          bundle install
      - uses: tibdex/github-app-token@v1
        id: gh_token
        with:
          app_id: ${{ secrets.SIDER_INTERNAL_BOT_APP_ID }}
          private_key: ${{ secrets.SIDER_INTERNAL_BOT_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump bundler from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}
          title: Bump bundler from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}
          body: |
            - https://github.com/rubygems/rubygems/releases/tag/bundler-v${{ env.LATEST_VERSION }}
            - https://github.com/rubygems/rubygems/blob/bundler-v${{ env.LATEST_VERSION }}/bundler/CHANGELOG.md
            - https://my.diffend.io/gems/bundler/${{ env.CURRENT_VERSION }}/${{ env.LATEST_VERSION }}
          branch: bump-bundler
          labels: dependencies,ruby
          token: ${{ steps.gh_token.outputs.token }}
        env:
          CURRENT_VERSION: ${{ steps.current_version.outputs.value }}
          LATEST_VERSION: ${{ steps.latest_version.outputs.value }}
